# -*- coding: utf-8 -*-
"""PrakStatis7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18gdOTAagpwp0dW3P6KK2g6ui81mk3ccq
"""

from google.colab import files
import pandas as pd

upload = files.upload()

data_reza = pd.read_csv('/content/titanic.csv')

print(data)

data1 = data.loc[:,['Age','Pclass','Survived']]
print(data1)

data2 = data[['Age', 'Pclass', 'Survived']]
data2.plot(title='Persebaran Data', x='Age', y='Pclass', kind='scatter', c='Survived', colormap='Paired')

data3 = data[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
penumpang=data3.groupby('Pclass')['Name'].nunique()
print('Jumlah Penumpang:\n', penumpang)

data4 = data[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
notsurvivedpassanger=data4['Pclass'].loc[data['Survived']==0]
print('Penumpang yang tidak survived:\n', notsurvivedpassanger.value_counts())
survivedpassanger=data4['Pclass'].loc[data['Survived']==1]
print('\nPenumpang yang survived:\n', survivedpassanger.value_counts())

data3 = data_reza[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
penumpang=data3.groupby('Sex')['Name'].nunique()
print('Jumlah Penumpang:\n', penumpang)

data4 = data_reza[['Name', 'Sex', 'Age', 'Pclass', 'Fare']]
notsurvivedpassanger=data4['Sex'].loc[data_reza['Survived']==0]
print('Penumpang yang tidak survived:\n', notsurvivedpassanger.value_counts())
survivedpassanger=data4['Sex'].loc[data_reza['Survived']==1]
print('\nPenumpang yang survived:\n', survivedpassanger.value_counts())